
services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "8000:8000"
    networks:
      - shared-crm-network

volumes:
  crm-data:
    driver: local

networks:
  shared-crm-network:
    driver: bridge
    name: shared-crm-network


